spring:
  datasource:
    mysql:
      jdbc-url: jdbc:mysql://localhost:3306/mysql_db
      username: root
      password: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver

    postgres:
      jdbc-url: jdbc:postgresql://localhost:5432/postgres_db
      username: postgres
      password: postgresql
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
